<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.8">
  <POU Name="IsBetween" Id="{30980012-edae-416d-9aac-47ae41f64e5a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION IsBetween : BOOL
VAR_INPUT
	value: 	LREAL;
	minV:	LREAL;
	maxV:	LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IsBetween := value > minV AND value < maxV;]]></ST>
    </Implementation>
    <LineIds Name="IsBetween">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>