<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="CurrentF_VelocityCoeff" Id="{1b258ca5-4c38-0abc-3788-dd7e914aa2ca}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION CurrentF_VelocityCoeff : LREAL
VAR_INPUT
    Velocity    : LREAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[CurrentF_VelocityCoeff  := EXPT(Velocity,2);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>